FROM tensorflow/tensorflow:1.12.0-gpu-py3

RUN apt-get update && apt-get install -y --no-install-recommends \
	# ec2metadata, for logging what machine we ran on
	cloud-utils && \
    	apt-get clean && \
    	rm -rf /var/lib/apt/lists/*


ADD requirements/requirements-py3.txt /install/requirements-py3.txt
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r /install/requirements-py3.txt

WORKDIR /notebooks

CMD /run_jupyter.sh --allow-root
